connect = False
with open('seed.txt') as f:
    seed = f.read()
    print(seed)
seedinput = input("Please enter the seed generated by the server. This value should be 5 digits long: ")
if seed == seedinput:
    connect = True
    print('True')
    f.close()
else:
    connect = False
    print('False')
    f.close()